Add Pyright type checking as nonblocking CI step.

diff --git a/.github/workflows/py.yaml b/.github/workflows/py.yaml
--- a/.github/workflows/py.yaml
+++ b/.github/workflows/py.yaml
@@ -19,6 +19,8 @@ jobs:
           - "3.10"
           - "3.11"
           - "3.12"
+        node_version:
+          - "20"
 
     steps:
       - uses: actions/checkout@v4
@@ -26,15 +28,28 @@ jobs:
         uses: actions/setup-python@v5
         with:
           python-version: ${{ matrix.python-version }}
+      - name: Set up Node.js ${{ matrix.node-version }} for Pyright
+        uses: actions/setup-node@v4
+        with:
+          node-version: ${{ matrix.node-version }}
+          registry-url: "https://registry.npmjs.org"
+      - name: Set up pnpm
+        uses: pnpm/action-setup@v4
+        with:
+          version: 8
       - name: Install dependencies
         run: |
-          python -m pip install --upgrade pip setuptools build twine openai pylint
+          python -m pip install --upgrade pip setuptools build twine openai pylint==3.3.1
       - name: Test whether the Python SDK can be installed
         run: |
           python -m pip install -e ./py[all]
       - name: Test whether the Python SDK can be imported
         run: |
           python -c 'import braintrust'
+      - name: Type check the Python SDK
+        # TODO: Make Pyright errors fail the build.
+        run: |
+          pnpx pyright@1.1.388 --level error $(git ls-files '*.py') || true
       - name: Lint the Python SDK
         run: |
           pylint --errors-only $(git ls-files '*.py')
